/**
 * Convert Notion page to markdown file content
 */

import type { PageNode, PropertyValue } from "../notion/tree.ts";
import {
  blocksToMarkdown,
  type NotionBlock,
  type RenderContext,
  type DatabaseEntry,
} from "./blocks.ts";

export interface PageMarkdown {
  /** Page title */
  title: string;
  /** Full markdown content including frontmatter */
  content: string;
  /** Suggested filename (slugified title) */
  filename: string;
}

export interface ConvertOptions {
  /** Include YAML frontmatter */
  includeFrontmatter?: boolean;
  /** Include page title as H1 */
  includeTitle?: boolean;
}

const defaultOptions: ConvertOptions = {
  includeFrontmatter: true,
  includeTitle: true,
};

/** Warning comment added to top of generated files */
const GENERATED_HEADER = `<!-- 
  Auto-generated by notion-rsync. Do not edit manually.
  Changes will be overwritten on next sync.
-->`;

/**
 * Convert a PageNode to markdown
 */
export function pageToMarkdown(page: PageNode, options: ConvertOptions = {}): PageMarkdown {
  const opts = { ...defaultOptions, ...options };

  const parts: string[] = [];

  // Warning header
  parts.push(GENERATED_HEADER);

  // Frontmatter
  if (opts.includeFrontmatter) {
    parts.push(generateFrontmatter(page));
  }

  // Title
  if (opts.includeTitle) {
    parts.push(`# ${page.title}\n`);
  }

  // Build render context with database entries from children
  const context = buildRenderContext(page);

  // Content
  const content = blocksToMarkdown(page.blocks as NotionBlock[], context);
  if (content) {
    parts.push(content);
  }

  return {
    title: page.title,
    content: parts.join("\n"),
    filename: slugify(page.title) + ".md",
  };
}

/**
 * Build render context from page children
 * Maps database IDs to their entries (child pages)
 */
function buildRenderContext(page: PageNode): RenderContext {
  const databases = new Map<string, DatabaseEntry[]>();

  for (const child of page.children) {
    if (child.isDatabase) {
      // This child is a database - collect its entries
      const entries: DatabaseEntry[] = child.children.map((entry) => ({
        id: entry.id,
        title: entry.title,
        properties: entry.properties || {},
      }));

      // Store by both formats (with and without dashes)
      databases.set(child.id, entries);
      databases.set(child.id.replace(/-/g, ""), entries);
    }
  }

  return { databases };
}

/**
 * Generate YAML frontmatter
 */
function generateFrontmatter(page: PageNode): string {
  const lines = [
    "---",
    `notion_id: ${page.id}`,
    `title: "${escapeYamlString(page.title)}"`,
    `last_edited: ${page.lastEditedTime}`,
  ];

  // Add page properties from database
  if (page.properties) {
    for (const [key, value] of Object.entries(page.properties)) {
      const yamlValue = formatYamlValue(value);
      if (yamlValue !== null) {
        lines.push(`${slugifyKey(key)}: ${yamlValue}`);
      }
    }
  }

  lines.push("---", "");

  return lines.join("\n");
}

/**
 * Convert property key to valid YAML key (lowercase, underscores)
 */
function slugifyKey(key: string): string {
  return key
    .toLowerCase()
    .replace(/[^\w\s]/g, "")
    .replace(/\s+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

/**
 * Format a property value for YAML
 */
function formatYamlValue(value: PropertyValue): string | null {
  if (value === null || value === undefined) return null;

  if (typeof value === "boolean") return value.toString();
  if (typeof value === "number") return value.toString();

  if (Array.isArray(value)) {
    if (value.length === 0) return null;
    return `[${value.map((v) => `"${escapeYamlString(String(v))}"`).join(", ")}]`;
  }

  // String
  const str = String(value);
  if (!str) return null;
  return `"${escapeYamlString(str)}"`;
}

/**
 * Escape special characters in YAML strings
 */
function escapeYamlString(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

/**
 * Convert title to URL-safe filename
 */
export function slugify(text: string): string {
  return (
    text
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, "") // Remove special chars
      .replace(/\s+/g, "-") // Spaces to hyphens
      .replace(/-+/g, "-") // Multiple hyphens to single
      .replace(/^-|-$/g, "") // Trim hyphens
      .slice(0, 100) || // Limit length
    "untitled"
  );
}

/**
 * Generate a unique filename given existing filenames
 */
export function uniqueFilename(base: string, existing: Set<string>): string {
  if (!existing.has(base)) return base;

  const ext = base.endsWith(".md") ? ".md" : "";
  const name = base.replace(/\.md$/, "");

  let counter = 1;
  let candidate = `${name}-${counter}${ext}`;

  while (existing.has(candidate)) {
    counter++;
    candidate = `${name}-${counter}${ext}`;
  }

  return candidate;
}
