/**
 * Tests for markdown frontmatter / body parsing.
 */

import { describe, it, expect } from "bun:test";
import { parseMarkdownFile } from "../frontmatter.ts";

describe("parseMarkdownFile", () => {
  it("extracts notion_id and title from frontmatter", () => {
    const raw = `---
notion_id: abc-123
title: "My Page"
last_edited: 2026-01-01T00:00:00Z
---

Some content.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.notionId).toBe("abc-123");
    expect(parsed.title).toBe("My Page");
    expect(parsed.body.trim()).toBe("Some content.");
  });

  it("strips the generated-file header comment", () => {
    const raw = `<!--
  Auto-generated by notion-rsync. Do not edit manually.
-->
---
title: "T"
notion_id: x
---

# T

Body.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.title).toBe("T");
    expect(parsed.body.trim()).toBe("Body.");
    expect(parsed.body).not.toContain("# T");
    expect(parsed.body).not.toContain("Auto-generated");
  });

  it("uses the first H1 as title when no frontmatter", () => {
    const parsed = parseMarkdownFile("# Hand Authored\n\nHello.");
    expect(parsed.title).toBe("Hand Authored");
    expect(parsed.notionId).toBeNull();
    expect(parsed.body.trim()).toBe("Hello.");
  });

  it("returns null title for a file with no frontmatter or H1", () => {
    const parsed = parseMarkdownFile("just text");
    expect(parsed.title).toBeNull();
    expect(parsed.body.trim()).toBe("just text");
  });

  it("does not strip a non-leading H1", () => {
    const raw = `Intro paragraph.

# A Section

More.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.title).toBe("A Section");
    expect(parsed.body).toContain("# A Section");
  });

  it("parses array frontmatter values", () => {
    const raw = `---
title: "T"
tags: ["a", "b"]
---
x
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.frontmatter["tags"]).toEqual(["a", "b"]);
  });
});
