/**
 * Tests for markdown frontmatter / body parsing.
 */

import { describe, it, expect } from "bun:test";
import { parseMarkdownFile, upsertFrontmatter } from "../frontmatter.ts";

describe("parseMarkdownFile", () => {
  it("extracts notion_id and title from frontmatter", () => {
    const raw = `---
notion_id: abc-123
title: "My Page"
last_edited: 2026-01-01T00:00:00Z
---

Some content.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.notionId).toBe("abc-123");
    expect(parsed.title).toBe("My Page");
    expect(parsed.body.trim()).toBe("Some content.");
  });

  it("strips the generated-file header comment", () => {
    const raw = `<!--
  Auto-generated by notion-rsync. Do not edit manually.
-->
---
title: "T"
notion_id: x
---

# T

Body.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.title).toBe("T");
    expect(parsed.body.trim()).toBe("Body.");
    expect(parsed.body).not.toContain("# T");
    expect(parsed.body).not.toContain("Auto-generated");
  });

  it("uses the first H1 as title when no frontmatter", () => {
    const parsed = parseMarkdownFile("# Hand Authored\n\nHello.");
    expect(parsed.title).toBe("Hand Authored");
    expect(parsed.notionId).toBeNull();
    expect(parsed.body.trim()).toBe("Hello.");
  });

  it("returns null title for a file with no frontmatter or H1", () => {
    const parsed = parseMarkdownFile("just text");
    expect(parsed.title).toBeNull();
    expect(parsed.body.trim()).toBe("just text");
  });

  it("does not strip a non-leading H1", () => {
    const raw = `Intro paragraph.

# A Section

More.
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.title).toBe("A Section");
    expect(parsed.body).toContain("# A Section");
  });

  it("parses array frontmatter values", () => {
    const raw = `---
title: "T"
tags: ["a", "b"]
---
x
`;
    const parsed = parseMarkdownFile(raw);
    expect(parsed.frontmatter["tags"]).toEqual(["a", "b"]);
  });
});

describe("upsertFrontmatter", () => {
  it("creates frontmatter when none exists", () => {
    const out = upsertFrontmatter("# Guide\n\nBody.\n", {
      notion_id: "abc-123",
      title: '"Guide"',
    });
    expect(out).toBe('---\nnotion_id: abc-123\ntitle: "Guide"\n---\n\n# Guide\n\nBody.\n');
  });

  it("updates an existing key and preserves the rest", () => {
    const raw = `---
notion_id: old
title: "Guide"
status: "Draft"
---

Body.
`;
    const out = upsertFrontmatter(raw, { notion_id: "new" });
    expect(out).toContain("notion_id: new");
    expect(out).toContain('title: "Guide"');
    expect(out).toContain('status: "Draft"');
    expect(out).toContain("Body.");
  });

  it("appends a missing key without disturbing others", () => {
    const raw = `---
title: "Guide"
---

Body.
`;
    const out = upsertFrontmatter(raw, { notion_id: "abc" });
    expect(out).toContain('title: "Guide"');
    expect(out).toContain("notion_id: abc");
  });

  it("preserves a leading generated-header comment", () => {
    const raw = `<!--
  Auto-generated. Do not edit.
-->
---
title: "Guide"
---

Body.
`;
    const out = upsertFrontmatter(raw, { notion_id: "abc" });
    expect(out.startsWith("<!--")).toBe(true);
    expect(out).toContain("notion_id: abc");
  });

  it("is stable when the key already has the target value", () => {
    const raw = `---
notion_id: abc
title: "Guide"
---

Body.
`;
    expect(upsertFrontmatter(raw, { notion_id: "abc", title: '"Guide"' })).toBe(raw);
  });

  it("round-trips through parseMarkdownFile", () => {
    const stamped = upsertFrontmatter("# Guide\n\nBody.\n", {
      notion_id: "abc-123",
      title: '"Guide"',
    });
    const parsed = parseMarkdownFile(stamped);
    expect(parsed.notionId).toBe("abc-123");
    expect(parsed.title).toBe("Guide");
    expect(parsed.body.trim()).toBe("Body.");
  });
});
